# Generated by Django 4.2.1 on 2023-06-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_wishlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Order Pending"),
                    ("ACCEPTED", "Order Accepted"),
                    ("PACKED", "Your Order Is Packed"),
                    ("ON THE WAY", "On The Way To Your Nearest Hub"),
                    ("DELIVERED", " Order Is Delivered"),
                    ("CANCEL ORDER", " Order Is Cancelled"),
                ],
                default="PENDING",
                max_length=50,
            ),
        ),
    ]
