# Generated by Django 4.2.1 on 2023-06-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraddress",
            name="address_line1",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="useraddress",
            name="address_line2",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
