# Generated by Django 4.2.1 on 2023-06-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_useraddress_address_line1_useraddress_address_line2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraddress",
            name="profile",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/userprofile/"
            ),
        ),
    ]
