# Generated by Django 4.2.1 on 2023-06-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_alter_useraddress_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraddress",
            name="profile",
            field=models.ImageField(null=True, upload_to="images/userprofile/"),
        ),
    ]
