# Generated by Django 4.2.1 on 2023-06-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_alter_useraddress_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useraddress",
            name="profile",
        ),
        migrations.AddField(
            model_name="useraddress",
            name="state",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
