# Generated by Django 4.2.1 on 2023-06-04 16:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_remove_useraddress_profile_useraddress_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useraddress",
            name="district",
        ),
        migrations.RemoveField(
            model_name="useraddress",
            name="landmark",
        ),
        migrations.RemoveField(
            model_name="useraddress",
            name="place",
        ),
        migrations.RemoveField(
            model_name="useraddress",
            name="zipcode",
        ),
    ]
